server:
  port: 9999
  undertow:
    io-threads: 1
    worker-threads: 4

spring:
  kafka:
    bootstrap-servers: kafka-online1:9092,kafka-online2:9092,kafka-online3:9092
    listener:
      concurrency: 2
      ack-mode: manual
    consumer:
      group-id: console
      enable-auto-commit: false
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all
      compression-type: lz4

kafka:
  producer:
    concurrency: 3
  listener:
    auto-startup: true

logging.file: springboot-kafka.log
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.kafka: INFO
  file:
    max-size: 256MB
    max-history: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
