server:
  port: 9999
  undertow:
    io-threads: 1
    worker-threads: 4

spring:
  kafka:
    bootstrap-servers: kafka-test:9092
    listener:
      concurrency: 1
      ack-mode: manual
    consumer:
      group-id: console
      auto-offset-reset: latest
      enable-auto-commit: false
    producer:
      compression-type: lz4
      retries: 3
      acks: all

kafka:
  producer:
    concurrency: 3
  listener:
    auto-startup: true

logging.file: springboot-kafka.log
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.kafka: INFO
  file:
    max-size: 256MB
    max-history: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
