server:
  port: 8000
  undertow:
    io-threads: 2
    worker-threads: 16

spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: springboot.admin

logging.file: springboot-admin.log
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.admin: DEBUG
  file:
    max-size: 512MB
    max-history: 3

