server:
  port: 8000
  undertow:
    io-threads: 1
    worker-threads: 4

spring:
  application:
    name: ADMIN
  security:
    user:
      name: admin
      password: springboot.admin

logging.file: springboot-admin.log
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.admin: DEBUG
  file:
    max-size: 512MB
    max-history: 3

