server:
  port: 9999

spring:
  application:
    name: security
  boot:
    admin:
      client:
        url: http://localhost:8000
        instance:
          prefer-ip: true
        username: admin
        password: springboot.admin
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
    hikari:
      pool-name: MySQLHikari
  redis:
    host: localhost
    port: 6379
    database: 0
    password: Redis123.com
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
  security:
    user:
      name: admin
      password: admin

  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.niuchaoqun.springboot.security.entity,com.niuchaoqun.springboot.security.dto.form
mapper:
  identity: mysql
  not-empty: false
  wrap-keyword: "`{0}`"
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging.file: springboot-security.log
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.security: DEBUG
  file:
    max-size: 256MB
    max-history: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
web:
  jwt:
    url: /api/**
    login-url: /api/login
    secret: secret
    expiration: 3600000
    header: Jwt-Authorization
  config:
    table-cache:
      - role
      - setting


