server:
  port: 9999

spring:
  application:
    name: security
  boot:
    admin:
      client:
        url: http://localhost:8000
        instance:
          prefer-ip: true
        username: admin
        password: springboot.admin
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: MySQLHikari
  security:
    user:
      name: admin
      password: admin


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.niuchaoqun.springboot.security.entity
mapper:
  identity: mysql
  not-empty: false
  wrap-keyword: "`{0}`"
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

jwt:
  url: /jwt/**
  login-url: /jwt/login
  secret: secret
  expiration: 3600000
  header: Jwt-Authorization

logging.file: springboot-security.log
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.security: DEBUG
  file:
    max-size: 256MB
    max-history: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


