server:
  port: 9999

spring:
  application:
    name: SECURITY
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
  security:
    user:
      name: admin
      password: admin


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.niuchaoqun.springboot.entity
mapper:
  identity: mysql
  not-empty: false
  wrap-keyword: "`{0}`"
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


jwt:
  url: /jwt/**
  login-url: /jwt/login
  secret: secret
  expiration: 3600000
  header: Authorization


