server:
  port: 9999

spring:
  application:
    name: mybatis-common
  boot:
    admin:
      client:
        url: http://localhost:8000
        instance:
          prefer-ip: true
        username: admin
        password: springboot.admin
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
    hikari:
      pool-name: MySQLHikari

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.niuchaoqun.springboot.mybatis.common.entity
mapper:
  identity: mysql
  not-empty: false
  wrap-keyword: "`{0}`"
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging.file: springboot-mybatis-common.log
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.mybatis.common: DEBUG
  file:
    max-size: 256MB
    max-history: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always