server:
  port: 9999

spring:
  application:
    name: security
  boot:
    admin:
      client:
        url: http://localhost:8000
        instance:
          prefer-ip: true
        username: admin
        password: springboot.admin
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
    hikari:
      pool-name: MySQLHikari
  redis:
    host: localhost
    port: 6379
    database: 0
    password: Redis123.com
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
  main:
    allow-bean-definition-overriding: true

#swagger:
#  basic:
#    enable: true
#    username: admin
#    password: swagger

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.niuchaoqun.springboot.security.entity,com.niuchaoqun.springboot.security.dto.form
mapper:
  identity: mysql
  not-empty: false
  wrap-keyword: "`{0}`"
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging.file: springboot-security.log
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.niuchaoqun.springboot.security: DEBUG
  file:
    max-size: 256MB
    max-history: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
web:
  jwt:
    url: /api/**
    secret: secret
    expiration: 86400000
    header: Jwt-Auth
  jwt-ignore:
    posts:
      - /api/auth/login
      - /api/auth/ping
    patterns:
      - /api/ignore/**
  basic:
    url: /basic/**
    user: admin
    password: password
  openapi:
    url: /openapi/**
    header-key: Openapi-Auth
    header-value: access
    error: Openapi auth error
  config:
    table-cache:
      - role
      - setting


