server:
  port: 9999
  undertow:
    io-threads: 1
    worker-threads: 8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:schema/tables_mysql_innodb.sql
    properties:
      org.quartz.scheduler.instanceName: MyScheduler
      org.quartz.threadPool.threadCount: 2
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO