server:
  port: 9999
  undertow:
    io-threads: 2
    worker-threads: 16

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password: Redis123.com
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  session:
    store-type: redis
    timeout: 3600

mybatis:
  type-aliases-package: com.niuchaoqun.springboot.redis.entity
  mapper-locations: classpath:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  identity: mysql
  not-empty: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
